version: '3.8'

services:
  api:
    build: ./src
    env_file:
      - .env
    restart: always
    container_name: notes-api
    volumes:
      - ./src:/app
    ports:
      - "8010:8000"
    networks:
      - telegram_notes_net

  db:
    image: postgres:15.2
    container_name: notes-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5431:5432"
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
    networks:
      - telegram_notes_net

  telegram_bot:
    build: ./src
    volumes:
      - ./src:/app
    entrypoint: python telegram_bot/bot.py
    restart: always
    container_name: telegram-notes-bot
    env_file:
      - .env
    networks:
      - telegram_notes_net

networks:
  telegram_notes_net:
    external:
      name: telegram_notes_net
