"""users

Revision ID: 59f93e7c4bc8
Revises: f206543ceeae
Create Date: 2024-09-20 06:55:03.233142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59f93e7c4bc8'
down_revision: Union[str, None] = 'f206543ceeae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('telegram_username', sa.String(length=128), nullable=True),
    sa.Column('telegram_chat_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_user_id'), 'users_user', ['id'], unique=False)
    op.create_index(op.f('ix_users_user_login'), 'users_user', ['login'], unique=True)
    op.add_column('notes_note', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'notes_note', 'users_user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes_note', type_='foreignkey')
    op.drop_column('notes_note', 'user_id')
    op.drop_index(op.f('ix_users_user_login'), table_name='users_user')
    op.drop_index(op.f('ix_users_user_id'), table_name='users_user')
    op.drop_table('users_user')
    # ### end Alembic commands ###
