"""telegram token and telegram id

Revision ID: 8da2264825a2
Revises: a1dde2b8ed6e
Create Date: 2024-09-25 20:19:13.494098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8da2264825a2'
down_revision: Union[str, None] = 'a1dde2b8ed6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_user', sa.Column('telegram_link_token', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_user', 'telegram_link_token')
    # ### end Alembic commands ###
