"""user telegram id

Revision ID: a1dde2b8ed6e
Revises: 35a8da65727d
Create Date: 2024-09-25 18:35:36.240724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1dde2b8ed6e'
down_revision: Union[str, None] = '35a8da65727d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_user', sa.Column('telegram_id', sa.String(), nullable=True))
    op.drop_column('users_user', 'telegram_chat_id')
    op.drop_column('users_user', 'telegram_username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_user', sa.Column('telegram_username', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('users_user', sa.Column('telegram_chat_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('users_user', 'telegram_id')
    # ### end Alembic commands ###
